#!/usr/bin/env python3
# This is called in the ./install/install.sh script
import json
import os
import sys

# This is necessary for the import below to work
root_dir = os.path.abspath(os.path.dirname(__file__) + '/..')
sys.path.append(root_dir)

from pcc.config import Config
from pcc.directoryutils import DirectoryUtils

receivers = Config.get_or_throw('receivers')

web_app_config = {'receivers': receivers}
web_app_config = json.dumps(web_app_config)
file = open(DirectoryUtils().root_dir + "/app/src/config.json", "w")
file.write(web_app_config)
file.close()
